// <auto-generated />
using System;
using SampleApp.Phones.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SampleApp.Migrations
{
    [DbContext(typeof(TspDatabaseContext))]
    [Migration("20181225171513_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SampleApp.Phones.Data.Call", b =>
                {
                    b.Property<int>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("Duration");

                    b.Property<int>("PhoneId");

                    b.HasKey("CallId");

                    b.HasIndex("PhoneId");

                    b.ToTable("Calls");

                    b.HasData(
                        new
                        {
                            CallId = 1,
                            Date = new DateTime(2018, 12, 14, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(1930),
                            Duration = 4,
                            PhoneId = 1
                        },
                        new
                        {
                            CallId = 2,
                            Date = new DateTime(2018, 12, 21, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3378),
                            Duration = 14,
                            PhoneId = 2
                        },
                        new
                        {
                            CallId = 3,
                            Date = new DateTime(2018, 12, 7, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3457),
                            Duration = 14,
                            PhoneId = 3
                        },
                        new
                        {
                            CallId = 4,
                            Date = new DateTime(2018, 12, 13, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3514),
                            Duration = 2,
                            PhoneId = 4
                        },
                        new
                        {
                            CallId = 5,
                            Date = new DateTime(2018, 12, 11, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3582),
                            Duration = 14,
                            PhoneId = 5
                        },
                        new
                        {
                            CallId = 6,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3638),
                            Duration = 8,
                            PhoneId = 6
                        },
                        new
                        {
                            CallId = 7,
                            Date = new DateTime(2018, 12, 13, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3812),
                            Duration = 4,
                            PhoneId = 7
                        },
                        new
                        {
                            CallId = 8,
                            Date = new DateTime(2018, 12, 19, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3867),
                            Duration = 19,
                            PhoneId = 8
                        },
                        new
                        {
                            CallId = 9,
                            Date = new DateTime(2018, 12, 21, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3922),
                            Duration = 17,
                            PhoneId = 9
                        },
                        new
                        {
                            CallId = 10,
                            Date = new DateTime(2018, 12, 23, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3976),
                            Duration = 19,
                            PhoneId = 10
                        },
                        new
                        {
                            CallId = 11,
                            Date = new DateTime(2018, 11, 29, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4027),
                            Duration = 18,
                            PhoneId = 11
                        },
                        new
                        {
                            CallId = 12,
                            Date = new DateTime(2018, 12, 21, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4077),
                            Duration = 14,
                            PhoneId = 12
                        },
                        new
                        {
                            CallId = 13,
                            Date = new DateTime(2018, 12, 14, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4127),
                            Duration = 17,
                            PhoneId = 13
                        },
                        new
                        {
                            CallId = 14,
                            Date = new DateTime(2018, 12, 3, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4177),
                            Duration = 18,
                            PhoneId = 14
                        },
                        new
                        {
                            CallId = 15,
                            Date = new DateTime(2018, 12, 9, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4228),
                            Duration = 19,
                            PhoneId = 15
                        },
                        new
                        {
                            CallId = 16,
                            Date = new DateTime(2018, 12, 18, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4278),
                            Duration = 16,
                            PhoneId = 16
                        },
                        new
                        {
                            CallId = 17,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4388),
                            Duration = 1,
                            PhoneId = 17
                        },
                        new
                        {
                            CallId = 18,
                            Date = new DateTime(2018, 12, 3, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4441),
                            Duration = 9,
                            PhoneId = 18
                        },
                        new
                        {
                            CallId = 19,
                            Date = new DateTime(2018, 12, 19, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4492),
                            Duration = 7,
                            PhoneId = 19
                        },
                        new
                        {
                            CallId = 20,
                            Date = new DateTime(2018, 12, 8, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4542),
                            Duration = 6,
                            PhoneId = 20
                        },
                        new
                        {
                            CallId = 21,
                            Date = new DateTime(2018, 12, 13, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4592),
                            Duration = 7,
                            PhoneId = 21
                        },
                        new
                        {
                            CallId = 22,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4643),
                            Duration = 16,
                            PhoneId = 22
                        },
                        new
                        {
                            CallId = 23,
                            Date = new DateTime(2018, 12, 15, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4693),
                            Duration = 14,
                            PhoneId = 23
                        },
                        new
                        {
                            CallId = 24,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4743),
                            Duration = 6,
                            PhoneId = 24
                        },
                        new
                        {
                            CallId = 25,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4793),
                            Duration = 13,
                            PhoneId = 25
                        },
                        new
                        {
                            CallId = 26,
                            Date = new DateTime(2018, 12, 21, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4886),
                            Duration = 16,
                            PhoneId = 26
                        },
                        new
                        {
                            CallId = 27,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4936),
                            Duration = 2,
                            PhoneId = 27
                        },
                        new
                        {
                            CallId = 28,
                            Date = new DateTime(2018, 11, 28, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4986),
                            Duration = 3,
                            PhoneId = 28
                        },
                        new
                        {
                            CallId = 29,
                            Date = new DateTime(2018, 12, 6, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5037),
                            Duration = 17,
                            PhoneId = 29
                        },
                        new
                        {
                            CallId = 30,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5087),
                            Duration = 7,
                            PhoneId = 30
                        },
                        new
                        {
                            CallId = 31,
                            Date = new DateTime(2018, 12, 19, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5137),
                            Duration = 6,
                            PhoneId = 31
                        },
                        new
                        {
                            CallId = 32,
                            Date = new DateTime(2018, 11, 28, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5187),
                            Duration = 15,
                            PhoneId = 32
                        },
                        new
                        {
                            CallId = 33,
                            Date = new DateTime(2018, 11, 28, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5241),
                            Duration = 17,
                            PhoneId = 33
                        },
                        new
                        {
                            CallId = 34,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5347),
                            Duration = 16,
                            PhoneId = 34
                        },
                        new
                        {
                            CallId = 35,
                            Date = new DateTime(2018, 12, 2, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5397),
                            Duration = 18,
                            PhoneId = 35
                        },
                        new
                        {
                            CallId = 36,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5489),
                            Duration = 15,
                            PhoneId = 36
                        },
                        new
                        {
                            CallId = 37,
                            Date = new DateTime(2018, 12, 6, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5541),
                            Duration = 19,
                            PhoneId = 37
                        },
                        new
                        {
                            CallId = 38,
                            Date = new DateTime(2018, 11, 29, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5591),
                            Duration = 18,
                            PhoneId = 38
                        },
                        new
                        {
                            CallId = 39,
                            Date = new DateTime(2018, 12, 16, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5642),
                            Duration = 1,
                            PhoneId = 39
                        },
                        new
                        {
                            CallId = 40,
                            Date = new DateTime(2018, 12, 14, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5693),
                            Duration = 17,
                            PhoneId = 40
                        },
                        new
                        {
                            CallId = 41,
                            Date = new DateTime(2018, 12, 16, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5743),
                            Duration = 8,
                            PhoneId = 41
                        },
                        new
                        {
                            CallId = 42,
                            Date = new DateTime(2018, 12, 3, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5794),
                            Duration = 4,
                            PhoneId = 42
                        },
                        new
                        {
                            CallId = 43,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5844),
                            Duration = 9,
                            PhoneId = 43
                        },
                        new
                        {
                            CallId = 44,
                            Date = new DateTime(2018, 12, 7, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5934),
                            Duration = 5,
                            PhoneId = 44
                        },
                        new
                        {
                            CallId = 45,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5988),
                            Duration = 6,
                            PhoneId = 45
                        },
                        new
                        {
                            CallId = 46,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6038),
                            Duration = 9,
                            PhoneId = 46
                        },
                        new
                        {
                            CallId = 47,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6089),
                            Duration = 13,
                            PhoneId = 47
                        },
                        new
                        {
                            CallId = 48,
                            Date = new DateTime(2018, 12, 7, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6139),
                            Duration = 6,
                            PhoneId = 48
                        },
                        new
                        {
                            CallId = 49,
                            Date = new DateTime(2018, 12, 13, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6189),
                            Duration = 10,
                            PhoneId = 49
                        },
                        new
                        {
                            CallId = 50,
                            Date = new DateTime(2018, 12, 4, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6239),
                            Duration = 1,
                            PhoneId = 50
                        },
                        new
                        {
                            CallId = 51,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6289),
                            Duration = 3,
                            PhoneId = 51
                        },
                        new
                        {
                            CallId = 52,
                            Date = new DateTime(2018, 12, 2, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6391),
                            Duration = 11,
                            PhoneId = 52
                        },
                        new
                        {
                            CallId = 53,
                            Date = new DateTime(2018, 12, 20, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6444),
                            Duration = 11,
                            PhoneId = 53
                        },
                        new
                        {
                            CallId = 54,
                            Date = new DateTime(2018, 12, 17, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6495),
                            Duration = 6,
                            PhoneId = 54
                        },
                        new
                        {
                            CallId = 55,
                            Date = new DateTime(2018, 11, 28, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6599),
                            Duration = 16,
                            PhoneId = 55
                        },
                        new
                        {
                            CallId = 56,
                            Date = new DateTime(2018, 12, 22, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6650),
                            Duration = 6,
                            PhoneId = 56
                        },
                        new
                        {
                            CallId = 57,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6700),
                            Duration = 7,
                            PhoneId = 57
                        },
                        new
                        {
                            CallId = 58,
                            Date = new DateTime(2018, 12, 15, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6750),
                            Duration = 18,
                            PhoneId = 58
                        },
                        new
                        {
                            CallId = 59,
                            Date = new DateTime(2018, 11, 30, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6800),
                            Duration = 1,
                            PhoneId = 59
                        },
                        new
                        {
                            CallId = 60,
                            Date = new DateTime(2018, 12, 16, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6850),
                            Duration = 11,
                            PhoneId = 60
                        },
                        new
                        {
                            CallId = 61,
                            Date = new DateTime(2018, 12, 21, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6900),
                            Duration = 4,
                            PhoneId = 61
                        },
                        new
                        {
                            CallId = 62,
                            Date = new DateTime(2018, 12, 23, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6950),
                            Duration = 7,
                            PhoneId = 62
                        },
                        new
                        {
                            CallId = 63,
                            Date = new DateTime(2018, 12, 23, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7000),
                            Duration = 16,
                            PhoneId = 63
                        },
                        new
                        {
                            CallId = 64,
                            Date = new DateTime(2018, 12, 19, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7050),
                            Duration = 5,
                            PhoneId = 64
                        },
                        new
                        {
                            CallId = 65,
                            Date = new DateTime(2018, 12, 15, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7161),
                            Duration = 17,
                            PhoneId = 65
                        },
                        new
                        {
                            CallId = 66,
                            Date = new DateTime(2018, 11, 29, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7214),
                            Duration = 16,
                            PhoneId = 66
                        },
                        new
                        {
                            CallId = 67,
                            Date = new DateTime(2018, 12, 3, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7265),
                            Duration = 15,
                            PhoneId = 67
                        },
                        new
                        {
                            CallId = 68,
                            Date = new DateTime(2018, 12, 4, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7315),
                            Duration = 7,
                            PhoneId = 68
                        },
                        new
                        {
                            CallId = 69,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7365),
                            Duration = 12,
                            PhoneId = 69
                        },
                        new
                        {
                            CallId = 70,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7415),
                            Duration = 3,
                            PhoneId = 70
                        },
                        new
                        {
                            CallId = 71,
                            Date = new DateTime(2018, 12, 3, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7465),
                            Duration = 13,
                            PhoneId = 71
                        },
                        new
                        {
                            CallId = 72,
                            Date = new DateTime(2018, 12, 15, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7643),
                            Duration = 15,
                            PhoneId = 72
                        },
                        new
                        {
                            CallId = 73,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7694),
                            Duration = 19,
                            PhoneId = 73
                        },
                        new
                        {
                            CallId = 74,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7745),
                            Duration = 9,
                            PhoneId = 74
                        },
                        new
                        {
                            CallId = 75,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7795),
                            Duration = 14,
                            PhoneId = 75
                        },
                        new
                        {
                            CallId = 76,
                            Date = new DateTime(2018, 12, 2, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7846),
                            Duration = 16,
                            PhoneId = 76
                        },
                        new
                        {
                            CallId = 77,
                            Date = new DateTime(2018, 12, 21, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7896),
                            Duration = 19,
                            PhoneId = 77
                        },
                        new
                        {
                            CallId = 78,
                            Date = new DateTime(2018, 12, 4, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7946),
                            Duration = 2,
                            PhoneId = 78
                        },
                        new
                        {
                            CallId = 79,
                            Date = new DateTime(2018, 12, 9, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7995),
                            Duration = 17,
                            PhoneId = 79
                        },
                        new
                        {
                            CallId = 80,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8045),
                            Duration = 19,
                            PhoneId = 80
                        },
                        new
                        {
                            CallId = 81,
                            Date = new DateTime(2018, 12, 13, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8095),
                            Duration = 10,
                            PhoneId = 81
                        },
                        new
                        {
                            CallId = 82,
                            Date = new DateTime(2018, 11, 30, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8200),
                            Duration = 14,
                            PhoneId = 82
                        },
                        new
                        {
                            CallId = 83,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8251),
                            Duration = 14,
                            PhoneId = 83
                        },
                        new
                        {
                            CallId = 84,
                            Date = new DateTime(2018, 11, 28, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8301),
                            Duration = 3,
                            PhoneId = 84
                        },
                        new
                        {
                            CallId = 85,
                            Date = new DateTime(2018, 11, 30, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8350),
                            Duration = 18,
                            PhoneId = 85
                        },
                        new
                        {
                            CallId = 86,
                            Date = new DateTime(2018, 12, 4, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8400),
                            Duration = 18,
                            PhoneId = 86
                        },
                        new
                        {
                            CallId = 87,
                            Date = new DateTime(2018, 12, 7, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8450),
                            Duration = 19,
                            PhoneId = 87
                        },
                        new
                        {
                            CallId = 88,
                            Date = new DateTime(2018, 12, 23, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8500),
                            Duration = 14,
                            PhoneId = 88
                        },
                        new
                        {
                            CallId = 89,
                            Date = new DateTime(2018, 12, 24, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8549),
                            Duration = 5,
                            PhoneId = 89
                        },
                        new
                        {
                            CallId = 90,
                            Date = new DateTime(2018, 12, 13, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8599),
                            Duration = 9,
                            PhoneId = 90
                        },
                        new
                        {
                            CallId = 91,
                            Date = new DateTime(2018, 12, 9, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8649),
                            Duration = 2,
                            PhoneId = 91
                        },
                        new
                        {
                            CallId = 92,
                            Date = new DateTime(2018, 12, 12, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8754),
                            Duration = 6,
                            PhoneId = 92
                        },
                        new
                        {
                            CallId = 93,
                            Date = new DateTime(2018, 12, 19, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8807),
                            Duration = 3,
                            PhoneId = 93
                        },
                        new
                        {
                            CallId = 94,
                            Date = new DateTime(2018, 12, 2, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8857),
                            Duration = 13,
                            PhoneId = 94
                        },
                        new
                        {
                            CallId = 95,
                            Date = new DateTime(2018, 12, 20, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8907),
                            Duration = 13,
                            PhoneId = 95
                        },
                        new
                        {
                            CallId = 96,
                            Date = new DateTime(2018, 12, 20, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8957),
                            Duration = 12,
                            PhoneId = 96
                        },
                        new
                        {
                            CallId = 97,
                            Date = new DateTime(2018, 12, 15, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(9007),
                            Duration = 12,
                            PhoneId = 97
                        },
                        new
                        {
                            CallId = 98,
                            Date = new DateTime(2018, 12, 22, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(9057),
                            Duration = 18,
                            PhoneId = 98
                        },
                        new
                        {
                            CallId = 99,
                            Date = new DateTime(2018, 12, 2, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(9107),
                            Duration = 12,
                            PhoneId = 99
                        });
                });

            modelBuilder.Entity("SampleApp.Phones.Data.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Number")
                        .IsRequired();

                    b.HasKey("PhoneId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            PhoneId = 1,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 2,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 3,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 4,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 5,
                            Number = "37067999997"
                        },
                        new
                        {
                            PhoneId = 6,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 7,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 8,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 9,
                            Number = "37067999995"
                        },
                        new
                        {
                            PhoneId = 10,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 11,
                            Number = "37067999991"
                        },
                        new
                        {
                            PhoneId = 12,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 13,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 14,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 15,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 16,
                            Number = "37067999996"
                        },
                        new
                        {
                            PhoneId = 17,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 18,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 19,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 20,
                            Number = "37067999995"
                        },
                        new
                        {
                            PhoneId = 21,
                            Number = "37067999996"
                        },
                        new
                        {
                            PhoneId = 22,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 23,
                            Number = "37067999995"
                        },
                        new
                        {
                            PhoneId = 24,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 25,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 26,
                            Number = "37067999997"
                        },
                        new
                        {
                            PhoneId = 27,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 28,
                            Number = "37067999997"
                        },
                        new
                        {
                            PhoneId = 29,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 30,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 31,
                            Number = "37067999996"
                        },
                        new
                        {
                            PhoneId = 32,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 33,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 34,
                            Number = "37067999997"
                        },
                        new
                        {
                            PhoneId = 35,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 36,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 37,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 38,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 39,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 40,
                            Number = "37067999995"
                        },
                        new
                        {
                            PhoneId = 41,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 42,
                            Number = "37067999997"
                        },
                        new
                        {
                            PhoneId = 43,
                            Number = "37067999995"
                        },
                        new
                        {
                            PhoneId = 44,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 45,
                            Number = "37067999996"
                        },
                        new
                        {
                            PhoneId = 46,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 47,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 48,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 49,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 50,
                            Number = "37067999996"
                        },
                        new
                        {
                            PhoneId = 51,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 52,
                            Number = "37067999991"
                        },
                        new
                        {
                            PhoneId = 53,
                            Number = "37067999996"
                        },
                        new
                        {
                            PhoneId = 54,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 55,
                            Number = "37067999995"
                        },
                        new
                        {
                            PhoneId = 56,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 57,
                            Number = "37067999996"
                        },
                        new
                        {
                            PhoneId = 58,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 59,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 60,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 61,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 62,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 63,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 64,
                            Number = "37067999995"
                        },
                        new
                        {
                            PhoneId = 65,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 66,
                            Number = "37067999997"
                        },
                        new
                        {
                            PhoneId = 67,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 68,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 69,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 70,
                            Number = "37067999991"
                        },
                        new
                        {
                            PhoneId = 71,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 72,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 73,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 74,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 75,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 76,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 77,
                            Number = "37067999997"
                        },
                        new
                        {
                            PhoneId = 78,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 79,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 80,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 81,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 82,
                            Number = "37067999993"
                        },
                        new
                        {
                            PhoneId = 83,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 84,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 85,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 86,
                            Number = "37067999998"
                        },
                        new
                        {
                            PhoneId = 87,
                            Number = "37067999997"
                        },
                        new
                        {
                            PhoneId = 88,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 89,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 90,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 91,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 92,
                            Number = "37067999997"
                        },
                        new
                        {
                            PhoneId = 93,
                            Number = "37067999992"
                        },
                        new
                        {
                            PhoneId = 94,
                            Number = "37067999990"
                        },
                        new
                        {
                            PhoneId = 95,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 96,
                            Number = "37067999994"
                        },
                        new
                        {
                            PhoneId = 97,
                            Number = "37067999991"
                        },
                        new
                        {
                            PhoneId = 98,
                            Number = "37067999991"
                        },
                        new
                        {
                            PhoneId = 99,
                            Number = "37067999993"
                        });
                });

            modelBuilder.Entity("SampleApp.Phones.Data.Sms", b =>
                {
                    b.Property<int>("SmsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("PhoneId");

                    b.HasKey("SmsId");

                    b.HasIndex("PhoneId");

                    b.ToTable("Smses");

                    b.HasData(
                        new
                        {
                            SmsId = 1,
                            Date = new DateTime(2018, 12, 3, 19, 15, 12, 535, DateTimeKind.Local).AddTicks(2125),
                            PhoneId = 1
                        },
                        new
                        {
                            SmsId = 2,
                            Date = new DateTime(2018, 11, 30, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3310),
                            PhoneId = 2
                        },
                        new
                        {
                            SmsId = 3,
                            Date = new DateTime(2018, 12, 17, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3430),
                            PhoneId = 3
                        },
                        new
                        {
                            SmsId = 4,
                            Date = new DateTime(2018, 12, 20, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3494),
                            PhoneId = 4
                        },
                        new
                        {
                            SmsId = 5,
                            Date = new DateTime(2018, 12, 16, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3560),
                            PhoneId = 5
                        },
                        new
                        {
                            SmsId = 6,
                            Date = new DateTime(2018, 12, 9, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3619),
                            PhoneId = 6
                        },
                        new
                        {
                            SmsId = 7,
                            Date = new DateTime(2018, 12, 12, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3790),
                            PhoneId = 7
                        },
                        new
                        {
                            SmsId = 8,
                            Date = new DateTime(2018, 12, 4, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3847),
                            PhoneId = 8
                        },
                        new
                        {
                            SmsId = 9,
                            Date = new DateTime(2018, 12, 11, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3902),
                            PhoneId = 9
                        },
                        new
                        {
                            SmsId = 10,
                            Date = new DateTime(2018, 12, 24, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(3958),
                            PhoneId = 10
                        },
                        new
                        {
                            SmsId = 11,
                            Date = new DateTime(2018, 12, 21, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4009),
                            PhoneId = 11
                        },
                        new
                        {
                            SmsId = 12,
                            Date = new DateTime(2018, 12, 2, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4060),
                            PhoneId = 12
                        },
                        new
                        {
                            SmsId = 13,
                            Date = new DateTime(2018, 11, 30, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4110),
                            PhoneId = 13
                        },
                        new
                        {
                            SmsId = 14,
                            Date = new DateTime(2018, 12, 22, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4160),
                            PhoneId = 14
                        },
                        new
                        {
                            SmsId = 15,
                            Date = new DateTime(2018, 12, 7, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4210),
                            PhoneId = 15
                        },
                        new
                        {
                            SmsId = 16,
                            Date = new DateTime(2018, 12, 17, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4260),
                            PhoneId = 16
                        },
                        new
                        {
                            SmsId = 17,
                            Date = new DateTime(2018, 12, 11, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4368),
                            PhoneId = 17
                        },
                        new
                        {
                            SmsId = 18,
                            Date = new DateTime(2018, 11, 28, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4422),
                            PhoneId = 18
                        },
                        new
                        {
                            SmsId = 19,
                            Date = new DateTime(2018, 12, 7, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4474),
                            PhoneId = 19
                        },
                        new
                        {
                            SmsId = 20,
                            Date = new DateTime(2018, 12, 13, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4525),
                            PhoneId = 20
                        },
                        new
                        {
                            SmsId = 21,
                            Date = new DateTime(2018, 12, 23, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4575),
                            PhoneId = 21
                        },
                        new
                        {
                            SmsId = 22,
                            Date = new DateTime(2018, 12, 9, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4625),
                            PhoneId = 22
                        },
                        new
                        {
                            SmsId = 23,
                            Date = new DateTime(2018, 12, 22, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4675),
                            PhoneId = 23
                        },
                        new
                        {
                            SmsId = 24,
                            Date = new DateTime(2018, 12, 14, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4725),
                            PhoneId = 24
                        },
                        new
                        {
                            SmsId = 25,
                            Date = new DateTime(2018, 12, 6, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4775),
                            PhoneId = 25
                        },
                        new
                        {
                            SmsId = 26,
                            Date = new DateTime(2018, 12, 2, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4867),
                            PhoneId = 26
                        },
                        new
                        {
                            SmsId = 27,
                            Date = new DateTime(2018, 12, 22, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4919),
                            PhoneId = 27
                        },
                        new
                        {
                            SmsId = 28,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(4969),
                            PhoneId = 28
                        },
                        new
                        {
                            SmsId = 29,
                            Date = new DateTime(2018, 12, 15, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5020),
                            PhoneId = 29
                        },
                        new
                        {
                            SmsId = 30,
                            Date = new DateTime(2018, 12, 14, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5069),
                            PhoneId = 30
                        },
                        new
                        {
                            SmsId = 31,
                            Date = new DateTime(2018, 12, 11, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5120),
                            PhoneId = 31
                        },
                        new
                        {
                            SmsId = 32,
                            Date = new DateTime(2018, 12, 22, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5170),
                            PhoneId = 32
                        },
                        new
                        {
                            SmsId = 33,
                            Date = new DateTime(2018, 12, 12, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5222),
                            PhoneId = 33
                        },
                        new
                        {
                            SmsId = 34,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5326),
                            PhoneId = 34
                        },
                        new
                        {
                            SmsId = 35,
                            Date = new DateTime(2018, 12, 18, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5380),
                            PhoneId = 35
                        },
                        new
                        {
                            SmsId = 36,
                            Date = new DateTime(2018, 12, 23, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5453),
                            PhoneId = 36
                        },
                        new
                        {
                            SmsId = 37,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5523),
                            PhoneId = 37
                        },
                        new
                        {
                            SmsId = 38,
                            Date = new DateTime(2018, 12, 8, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5574),
                            PhoneId = 38
                        },
                        new
                        {
                            SmsId = 39,
                            Date = new DateTime(2018, 11, 30, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5624),
                            PhoneId = 39
                        },
                        new
                        {
                            SmsId = 40,
                            Date = new DateTime(2018, 12, 8, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5675),
                            PhoneId = 40
                        },
                        new
                        {
                            SmsId = 41,
                            Date = new DateTime(2018, 12, 22, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5725),
                            PhoneId = 41
                        },
                        new
                        {
                            SmsId = 42,
                            Date = new DateTime(2018, 12, 20, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5776),
                            PhoneId = 42
                        },
                        new
                        {
                            SmsId = 43,
                            Date = new DateTime(2018, 11, 28, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5826),
                            PhoneId = 43
                        },
                        new
                        {
                            SmsId = 44,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5876),
                            PhoneId = 44
                        },
                        new
                        {
                            SmsId = 45,
                            Date = new DateTime(2018, 12, 13, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(5970),
                            PhoneId = 45
                        },
                        new
                        {
                            SmsId = 46,
                            Date = new DateTime(2018, 12, 23, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6021),
                            PhoneId = 46
                        },
                        new
                        {
                            SmsId = 47,
                            Date = new DateTime(2018, 11, 30, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6071),
                            PhoneId = 47
                        },
                        new
                        {
                            SmsId = 48,
                            Date = new DateTime(2018, 12, 11, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6122),
                            PhoneId = 48
                        },
                        new
                        {
                            SmsId = 49,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6171),
                            PhoneId = 49
                        },
                        new
                        {
                            SmsId = 50,
                            Date = new DateTime(2018, 12, 13, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6222),
                            PhoneId = 50
                        },
                        new
                        {
                            SmsId = 51,
                            Date = new DateTime(2018, 12, 19, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6272),
                            PhoneId = 51
                        },
                        new
                        {
                            SmsId = 52,
                            Date = new DateTime(2018, 12, 19, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6359),
                            PhoneId = 52
                        },
                        new
                        {
                            SmsId = 53,
                            Date = new DateTime(2018, 12, 14, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6426),
                            PhoneId = 53
                        },
                        new
                        {
                            SmsId = 54,
                            Date = new DateTime(2018, 12, 16, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6477),
                            PhoneId = 54
                        },
                        new
                        {
                            SmsId = 55,
                            Date = new DateTime(2018, 12, 7, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6581),
                            PhoneId = 55
                        },
                        new
                        {
                            SmsId = 56,
                            Date = new DateTime(2018, 12, 16, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6632),
                            PhoneId = 56
                        },
                        new
                        {
                            SmsId = 57,
                            Date = new DateTime(2018, 12, 3, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6682),
                            PhoneId = 57
                        },
                        new
                        {
                            SmsId = 58,
                            Date = new DateTime(2018, 12, 4, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6732),
                            PhoneId = 58
                        },
                        new
                        {
                            SmsId = 59,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6782),
                            PhoneId = 59
                        },
                        new
                        {
                            SmsId = 60,
                            Date = new DateTime(2018, 11, 30, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6833),
                            PhoneId = 60
                        },
                        new
                        {
                            SmsId = 61,
                            Date = new DateTime(2018, 12, 3, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6882),
                            PhoneId = 61
                        },
                        new
                        {
                            SmsId = 62,
                            Date = new DateTime(2018, 12, 21, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6932),
                            PhoneId = 62
                        },
                        new
                        {
                            SmsId = 63,
                            Date = new DateTime(2018, 12, 18, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(6982),
                            PhoneId = 63
                        },
                        new
                        {
                            SmsId = 64,
                            Date = new DateTime(2018, 12, 24, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7032),
                            PhoneId = 64
                        },
                        new
                        {
                            SmsId = 65,
                            Date = new DateTime(2018, 12, 23, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7141),
                            PhoneId = 65
                        },
                        new
                        {
                            SmsId = 66,
                            Date = new DateTime(2018, 12, 7, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7197),
                            PhoneId = 66
                        },
                        new
                        {
                            SmsId = 67,
                            Date = new DateTime(2018, 12, 19, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7247),
                            PhoneId = 67
                        },
                        new
                        {
                            SmsId = 68,
                            Date = new DateTime(2018, 12, 14, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7297),
                            PhoneId = 68
                        },
                        new
                        {
                            SmsId = 69,
                            Date = new DateTime(2018, 12, 11, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7348),
                            PhoneId = 69
                        },
                        new
                        {
                            SmsId = 70,
                            Date = new DateTime(2018, 12, 20, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7398),
                            PhoneId = 70
                        },
                        new
                        {
                            SmsId = 71,
                            Date = new DateTime(2018, 12, 17, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7448),
                            PhoneId = 71
                        },
                        new
                        {
                            SmsId = 72,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7624),
                            PhoneId = 72
                        },
                        new
                        {
                            SmsId = 73,
                            Date = new DateTime(2018, 12, 2, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7676),
                            PhoneId = 73
                        },
                        new
                        {
                            SmsId = 74,
                            Date = new DateTime(2018, 12, 19, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7727),
                            PhoneId = 74
                        },
                        new
                        {
                            SmsId = 75,
                            Date = new DateTime(2018, 12, 18, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7777),
                            PhoneId = 75
                        },
                        new
                        {
                            SmsId = 76,
                            Date = new DateTime(2018, 12, 10, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7828),
                            PhoneId = 76
                        },
                        new
                        {
                            SmsId = 77,
                            Date = new DateTime(2018, 12, 23, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7878),
                            PhoneId = 77
                        },
                        new
                        {
                            SmsId = 78,
                            Date = new DateTime(2018, 12, 11, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7928),
                            PhoneId = 78
                        },
                        new
                        {
                            SmsId = 79,
                            Date = new DateTime(2018, 12, 15, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(7978),
                            PhoneId = 79
                        },
                        new
                        {
                            SmsId = 80,
                            Date = new DateTime(2018, 11, 28, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8028),
                            PhoneId = 80
                        },
                        new
                        {
                            SmsId = 81,
                            Date = new DateTime(2018, 12, 14, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8078),
                            PhoneId = 81
                        },
                        new
                        {
                            SmsId = 82,
                            Date = new DateTime(2018, 12, 12, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8181),
                            PhoneId = 82
                        },
                        new
                        {
                            SmsId = 83,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8233),
                            PhoneId = 83
                        },
                        new
                        {
                            SmsId = 84,
                            Date = new DateTime(2018, 12, 13, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8283),
                            PhoneId = 84
                        },
                        new
                        {
                            SmsId = 85,
                            Date = new DateTime(2018, 12, 3, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8333),
                            PhoneId = 85
                        },
                        new
                        {
                            SmsId = 86,
                            Date = new DateTime(2018, 12, 7, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8382),
                            PhoneId = 86
                        },
                        new
                        {
                            SmsId = 87,
                            Date = new DateTime(2018, 12, 18, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8432),
                            PhoneId = 87
                        },
                        new
                        {
                            SmsId = 88,
                            Date = new DateTime(2018, 12, 1, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8482),
                            PhoneId = 88
                        },
                        new
                        {
                            SmsId = 89,
                            Date = new DateTime(2018, 12, 21, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8531),
                            PhoneId = 89
                        },
                        new
                        {
                            SmsId = 90,
                            Date = new DateTime(2018, 12, 14, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8581),
                            PhoneId = 90
                        },
                        new
                        {
                            SmsId = 91,
                            Date = new DateTime(2018, 12, 22, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8631),
                            PhoneId = 91
                        },
                        new
                        {
                            SmsId = 92,
                            Date = new DateTime(2018, 12, 20, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8682),
                            PhoneId = 92
                        },
                        new
                        {
                            SmsId = 93,
                            Date = new DateTime(2018, 11, 30, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8789),
                            PhoneId = 93
                        },
                        new
                        {
                            SmsId = 94,
                            Date = new DateTime(2018, 12, 24, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8840),
                            PhoneId = 94
                        },
                        new
                        {
                            SmsId = 95,
                            Date = new DateTime(2018, 12, 5, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8890),
                            PhoneId = 95
                        },
                        new
                        {
                            SmsId = 96,
                            Date = new DateTime(2018, 12, 22, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8940),
                            PhoneId = 96
                        },
                        new
                        {
                            SmsId = 97,
                            Date = new DateTime(2018, 12, 7, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(8989),
                            PhoneId = 97
                        },
                        new
                        {
                            SmsId = 98,
                            Date = new DateTime(2018, 12, 21, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(9040),
                            PhoneId = 98
                        },
                        new
                        {
                            SmsId = 99,
                            Date = new DateTime(2018, 12, 11, 19, 15, 12, 538, DateTimeKind.Local).AddTicks(9090),
                            PhoneId = 99
                        });
                });

            modelBuilder.Entity("SampleApp.Phones.Data.Call", b =>
                {
                    b.HasOne("SampleApp.Phones.Data.Phone")
                        .WithMany("Calls")
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SampleApp.Phones.Data.Sms", b =>
                {
                    b.HasOne("SampleApp.Phones.Data.Phone")
                        .WithMany("Smses")
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
