version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Production"
          command: "./wait-for-it.sh db:1434 -- dotnet SampleApp.dll"
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
